version: 2.1

jobs:
  lint-backend:
    docker:
      - image: kkarczmarczyk/node-yarn:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd backend
      - run: yarn install
      - run: yarn lint
  lint-frontend:
    docker:
      - image: kkarczmarczyk/node-yarn:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd frontend
      - run: yarn install
      - run: yarn lint