version: 2.1

jobs:
  lint-backend:
    docker:
      - image: kkarczmarczyk/node-yarn:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd backend && yarn install
      - run: cd backend && yarn lint
  lint-frontend:
    docker:
      - image: kkarczmarczyk/node-yarn:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd frontend && yarn install
      - run: cd frontend && yarn lint
  build-backend:
    machine: true
    steps:
      - checkout
      - run: docker build -t helpdesk-backend backend
      - run: docker tag helpdesk-backend alpha.deltasystems.cz:5000/helpdesk-backend:latest
      - run: docker login -u circleci -p ${CONTAINER_REGISTRY_PASSWORD} alpha.deltasystems.cz:5000
      - run: docker push alpha.deltasystems.cz:5000/helpdesk-backend:latest
  build-backend-edge:
    machine: true
    steps:
      - checkout
      - run: docker build -t helpdesk-backend backend
      - run: docker tag helpdesk-backend alpha.deltasystems.cz:5000/helpdesk-backend:edge
      - run: docker login -u circleci -p ${CONTAINER_REGISTRY_PASSWORD} alpha.deltasystems.cz:5000
      - run: docker push alpha.deltasystems.cz:5000/helpdesk-backend:edge
  build-frontend:
    machine: true
    steps:
      - checkout
      - run: docker build -t helpdesk-frontend --build-arg REACT_APP_GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT} --build-arg REACT_APP_LOCALIZATION_ENDPOINT=${LOCALIZATION_ENDPOINT} --build-arg PORT=3000 frontend
      - run: docker tag helpdesk-frontend alpha.deltasystems.cz:5000/helpdesk-frontend:latest
      - run: docker login -u circleci -p ${CONTAINER_REGISTRY_PASSWORD} alpha.deltasystems.cz:5000
      - run: docker push alpha.deltasystems.cz:5000/helpdesk-frontend:latest
  build-frontend-edge:
    machine: true
    steps:
      - checkout
      - run: docker build -t helpdesk-frontend --build-arg REACT_APP_GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT} --build-arg REACT_APP_LOCALIZATION_ENDPOINT=${LOCALIZATION_ENDPOINT} --build-arg PORT=3000 frontend
      - run: docker tag helpdesk-frontend alpha.deltasystems.cz:5000/helpdesk-frontend:edge
      - run: docker login -u circleci -p ${CONTAINER_REGISTRY_PASSWORD} alpha.deltasystems.cz:5000
      - run: docker push alpha.deltasystems.cz:5000/helpdesk-frontend:edge
  deploy-backend:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '03:ee:20:fb:bc:84:7a:25:68:88:08:82:c6:f7:1a:dc'
      - run: ssh root@alpha.deltasystems.cz docker service update --image localhost:5000/helpdesk-backend helpdesk_backend
  deploy-frontend:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '03:ee:20:fb:bc:84:7a:25:68:88:08:82:c6:f7:1a:dc'
      - run: ssh root@alpha.deltasystems.cz docker service update --image localhost:5000/helpdesk-frontend helpdesk_frontend
workflows:
  version: 2
  lint:
    jobs:
    - lint-backend:
        filters:
          branches:
            only:
            - master
            - dev
            - /feature\/.*/
    - lint-frontend:
        filters:
          branches:
            only:
            - master
            - dev
            - /feature\/.*/
    - build-backend:
        requires: ['lint-backend']
        filters:
          branches:
            only:
              - master
    - build-backend-edge:
        requires: ['lint-backend']
        filters:
          branches:
            only:
              - dev
    - build-frontend:
        requires: ['lint-frontend']
        filters:
          branches:
            only:
              - master
    - build-frontend-edge:
        requires: ['lint-frontend']
        filters:
          branches:
            only:
              - dev
    - deploy-backend:
        requires: ['build-backend']
        filters:
          branches:
            only:
              - master
    - deploy-frontend:
        requires: ['build-frontend']
        filters:
          branches:
            only:
              - master
